### ISSUE TITLE
create API's for approved students

### ISSUE THREAD

**Issue by kmangesh49** [aissmstpo/TPO-Backend-App#4]
add API's for retrieving only approved students

**Comment by dheeraj-israni** [comment]
How to know if a student is approved or not?
Is there a flag "approved" in user document...?

**Comment by kmangesh49** [comment]
Yes there is field...plz connect the db using compass to get a overview of varoius field, collection in db

**Comment by dheeraj-israni** [comment]
![c1](https://user-images.githubusercontent.com/51269966/81187256-6d206d80-8fd1-11ea-89b1-7fbb306956c3.PNG)
Which field...
status...?

**Comment by Thoratshubham** [comment]
I have updated the approval for Student in the database plzz check.....![Screenshot (81)](https://user-images.githubusercontent.com/42400439/81195787-ed4bd080-8fdb-11ea-9daa-d5b742b89810.png)
!
